### ISSUE TITLE
Fyi some other alternative.

### ISSUE THREAD

**Issue by gzp79** [voliva/rational-arbitrary-precision#1]
After reading your post on rust weekly, I just wanted to notify you about a different concept. Based on the domain you are targeting, it could be an interesting addition for you : http://www.cs.cmu.edu/~quake/robust.html

(you may close the issue any time :) )

**Comment by voliva** [comment]
Hey @gzp-crey thanks for pointing at this one and sorry I couldn't answer earlier.

I took a quick look on the paper and it looked interesting, but I wanted to dig a bit deeper before commenting about it.

Anyway, thanks again, it's really interesting!
